module.exports = {
  User: require('./User'),
  Invite: require('./Invite'),
  Blog: require('./Blog'),
  Article: require('./Article'),
  Report: require('./Report'),
  Camp: require('./Camp'),
  TeamMember: require('./TeamMember'),
  Contact: require('./Contact'),
  GuideCategory: require('./GuideCategory'),
  DeskStory: require('./DeskStory'),
  SuccessStory: require('./SuccessStory'),
  Paper: require('./Paper'),
  ExplainerVideo: require('./ExplainerVideo'),
  RunningNow: require('./RunningNow'),
  ToldInFull: require('./ToldInFull'),
  AlsoOnRecord: require('./AlsoOnRecord'),
  PressMention: require('./PressMention'),
};
